### PR TITLE
zh_CN/doc/create.md: Fix missing ',' and NOTE Ambiguity

### PR DESCRIPTION
**Pull request by menggus**
- [] **ONLY** change English documents in the Pull Request, translations will be synced and translate them with https://translate.gorm.io/ or it will cause merge conflicts!

### What did this pull request do?

zh_CN/doc/create.md: Fix missing ',' and NOTE Ambiguity

### CODE REVIEW

**Comment by jinzhu** [comment]
ONLY change English documents in the Pull Request, translations will be synced and translate them with https://translate.gorm.io/ or it will cause merge conflicts!

**Comment by menggus** [comment]
OK!

There is no problem with the English document, but the translated Chinese is ambiguous；

please check: https://gorm.io/docs/create.html#Default-Values

english: "NOTE Any zero value like 0, '', false won't be saved into the database for those fields defined default value" 

chinese: 注意 像 0、''、false 等零值，不会将这些字段定义的默认值保存到数据库

**Comment by jinzhu** [comment]
You can change translations with https://translate.gorm.io/

**Comment by menggus** [comment]
Thanks for the hint

**Pull request closed without merging**
