### PR TITLE
fix bug: typo

### PR DESCRIPTION
**Pull request by jincheng9**
as titled.

### CODE REVIEW

**Comment by jincheng9** [comment]
@jinzhu Please help review this pull request. Thanks.

**Comment by jincheng9** [comment]
Maybe you can add me as this repo's committer. I can help reivew the commits. Thanks.

**Comment by jinzhu** [comment]
Hi @jincheng9 

You can only update translations from https://translate.gorm.io/

We will add you as a committer when you contributed for a while. thank you.

**Comment by jincheng9** [comment]
Thanks.

**Pull request closed without merging**
